version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
      PG_HOST_PORT: 5432
      PG_HOST: localhost
      POSTGRES_DB: covid-data
      POSTGRES_PASSWORD: postgres123
      POSTGRES_SCHEMA: public
      POSTGRES_USER: postgres
      PROJECT_NAME: ${PROJECT_NAME}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5
    networks:
      - mynetwork

  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=covid-data
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - mynetwork

networks:
  mynetwork:
